services:
  web:
    build: .
    container_name: the-blog-web
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: blogdb

  db:
    image: mysql:8.0
    container_name: the-blog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  db_data:
